# Generated by Django 5.2.15 on 2026-06-08 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Nome da categoria", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ItemCardapio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="Nome do item", max_length=200)),
                (
                    "descricao",
                    models.TextField(help_text="Descrição detalhada do item"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, help_text="Preço em reais", max_digits=8
                    ),
                ),
                (
                    "disponivel",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o item está disponível para pedido",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        help_text="Categoria à qual este item pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="cardapio.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Cardápio",
                "verbose_name_plural": "Itens do Cardápio",
                "ordering": ["categoria", "nome"],
            },
        ),
    ]
