# Generated by Django 5.2.15 on 2026-06-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcardapio",
            name="imagem",
            field=models.ImageField(
                blank=True,
                help_text="Foto do item (opcional)",
                null=True,
                upload_to="cardapio/",
            ),
        ),
    ]
