# Generated by Django 5.2.15 on 2026-06-08 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cardapio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que o pedido foi registrado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("em_preparo", "Em Preparo"),
                            ("pronto", "Pronto"),
                            ("entregue", "Entregue"),
                        ],
                        default="recebido",
                        help_text="Status atual do pedido no fluxo de preparo",
                        max_length=20,
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("cartao_credito", "Cartão de Crédito"),
                            ("cartao_debito", "Cartão de Débito"),
                            ("dinheiro", "Dinheiro"),
                            ("pix", "Pix"),
                        ],
                        help_text="Forma de pagamento escolhida pelo cliente",
                        max_length=20,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observações adicionais do cliente sobre o pedido",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente que realizou o pedido",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantidade do item no pedido"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Item do cardápio selecionado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.itemcardapio",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        help_text="Pedido ao qual este item pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
    ]
