# Generated by Django 6.0.6 on 2026-06-23 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_cartaosalvo"),
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cartao_utilizado",
            field=models.ForeignKey(
                blank=True,
                help_text="Cartão salvo usado no pagamento deste pedido",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="accounts.cartaosalvo",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("cartao_credito", "Cartão de Crédito"),
                    ("cartao_debito", "Cartão de Débito"),
                ],
                help_text="Forma de pagamento escolhida pelo cliente",
                max_length=20,
            ),
        ),
    ]
