# Generated by Django 6.0.6 on 2026-06-23 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartaoSalvo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apelido",
                    models.CharField(
                        help_text="Rótulo livre para identificar o cartão (ex.: Nubank, Visa final 1234)",
                        max_length=50,
                    ),
                ),
                (
                    "nome_titular",
                    models.CharField(
                        help_text="Nome impresso no cartão", max_length=200
                    ),
                ),
                (
                    "numero_mascarado",
                    models.CharField(
                        help_text="Últimos 4 dígitos mascarados (ex.: **** **** **** 1234)",
                        max_length=19,
                    ),
                ),
                (
                    "bandeira",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("elo", "Elo"),
                            ("amex", "American Express"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("credito", "Crédito"), ("debito", "Débito")],
                        max_length=10,
                    ),
                ),
                ("validade", models.CharField(help_text="MM/AAAA", max_length=7)),
                (
                    "cvv",
                    models.CharField(
                        help_text="Código de segurança — verificado no pagamento",
                        max_length=4,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Cliente dono do cartão",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartão Salvo",
                "verbose_name_plural": "Cartões Salvos",
                "ordering": ["apelido"],
            },
        ),
    ]
