"""
Django settings for restaurante_backend project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de ambiente do arquivo .env (apenas em desenvolvimento local).
# Em produção (PythonAnywhere), as variáveis são configuradas diretamente no painel.
if (BASE_DIR / ".env").exists():
    load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-h7#msyl+!st672kxa8(b991cq0$_3pzbex(3#xan%ig%ur+f@$",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Em desenvolvimento, defina DEBUG=True no .env. Em produção, não defina (padrão False).
DEBUG = os.environ.get("DEBUG", "False") == "True"

# Hosts permitidos — em produção inclui o domínio do PythonAnywhere.
# Lido do .env para facilitar ajuste sem alterar o código.
_allowed_hosts_env = os.environ.get(
    "ALLOWED_HOSTS",
    "cucinaitaliana.pythonanywhere.com,localhost,127.0.0.1",
)
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "rest_framework.authtoken",
    "django_rest_passwordreset",
    "cardapio",
    "accounts",
    "pedidos",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # deve vir antes de CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "restaurante_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "restaurante_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Diretório onde o collectstatic reúne todos os arquivos estáticos para produção.
# Necessário para o Swagger carregar seus CSS/JS após rodar: python manage.py collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

# Arquivos de mídia enviados pelos usuários (ex: fotos dos itens do cardápio)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework — autenticação por token sem permissão global
# (a proteção IsAuthenticated é aplicada seletivamente em cada view)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
}

# ---------------------------------------------------------------------------
# CORS 
# ---------------------------------------------------------------------------
# CORS_ALLOWED_ORIGINS lista as origens (domínios) autorizadas a fazer
# requisições à API. O valor vem da variável de ambiente CORS_ALLOWED_ORIGINS,
# que deve conter uma lista separada por vírgulas, sem espaços.
#   Desenvolvimento local: http://localhost:8080,http://127.0.0.1:8080
#   Produção: acrescentar o domínio do frontend publicado no PythonAnywhere.
# ---------------------------------------------------------------------------
_cors_origins_env = os.environ.get(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:8080,http://127.0.0.1:8080",
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_env.split(",") if o.strip()]

# ---------------------------------------------------------------------------
# Configuração de e-mail
# ---------------------------------------------------------------------------
# EMAIL_BACKEND_TIPO controla o destino dos e-mails:
#   'console' → imprime o e-mail no terminal (padrão para desenvolvimento)
#   'gmail'   → envia e-mail real via Gmail SMTP (usar em produção)
# ---------------------------------------------------------------------------
_EMAIL_BACKEND_TIPO = os.environ.get("EMAIL_BACKEND_TIPO", "console")

if _EMAIL_BACKEND_TIPO == "gmail":
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    # Desenvolvimento: e-mail aparece no terminal (sem envio real)
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
    DEFAULT_FROM_EMAIL = "noreply@restaurante.local"
